### ISSUE TITLE
Manually specifying ray origin & ray destination

### ISSUE THREAD

**Issue by aluo-x** [glotzerlab/fresnel#118]
I was curious if there is any mechanism to manually specify the ray origin/direction and retrieve the following:

Index of triangle intersection in a mesh (if any)
Location of the intersection (if any)
Index of rays that intersected (if any)

Basically something that can duplicate the output of Trimesh's [intersects_location](https://trimsh.org/trimesh.ray.ray_pyembree.html#trimesh.ray.ray_pyembree.RayMeshIntersector.intersects_location) but for first hit only. 

My motivation is to find a light-weight python based ray-mesh intersection library for my research. Trimesh's embree based CPU ray tracer is okay, but unfortunately CPU bound. There are many heavy weight frameworks (Mitsuba/Cycles/etc. etc.) that can accomplish the same goal, but the functionality they provide seems excessive.

**Comment by joaander** [comment]
Thanks for the request. This type of functionality would be useful for a range of other fresnel users - i.e. for determining what geometry is clicked on in an interactive widget.

Fresnel does not currently have this capability. Adding it would require writing a new type of Tracer class that implements the desired functionality. It could leverage the existing intersection checks and geometry specification, though the closest hit program will require a few additions to pass the geometry id's down the pipeline. 

You mention that another code you consider is CPU bound. Are other parts of your computation on the GPU already? How many rays do you expect to process in one call? If you need the highest possible performance you may be better off using OptiX directly to get complete control over where the data buffers are stored. I am concerned that an implementation in fresnel may not be significantly faster than a CPU based solution if it has to copy a very large buffer of ray parameters to the GPU and the per-ray results back on every invocation. The ray/geometry intersection tests to get only the first hit are *very* fast individually.

**Comment by aluo-x** [comment]
Good points all around.

My other computation is done on the GPU, either via generic libraries (pytorch), or via small CUDA kernels. Current Ray's bundles are probably 10K rays. Embree, being on the CPU already requires me to do 2 transfers between the GPU/CPU.

I have considered using Blender, since my offline pipeline already relies heavily on it. But having a blender instance send/receive data from a main process seems like a terrible idea efficiency wise (even more so than 2 device/host transfers).

But admittedly, my reasons for preferring not to use embree is more peculiar - my machines are more CPU bound than GPU bound...

Are there any files that you would advise on as a starting point?

**Comment by joaander** [comment]
If you are interested in rolling your own solution specific to your needs, I'd read up on Optix: https://developer.nvidia.com/blog/how-to-get-started-with-optix-7/

If you'd like to contribute this functionality to fresnel, look at `TracerDirect.*`. We will need to implement a new class along these lines that traces a) the given rays instead of those defined by the Scene's camera, and b) provides the hit information in output buffers instead of in an image. 

The first phase would be to get the new Tracer working. Later we can evaluate how best to provide direct GPU access to the data buffers (i.e. through cupy or the cuda array interface). Unfortunately, fresnel has not yet been rewritten for Optix 7.0 but I think there are some CUDA interoperability APIs even in Optix 6.5.

**Comment by aluo-x** [comment]
Will take a look later today. Have written simple CUDA kernels but haven't worked with Optix. I'll check out the documentation.
