### ISSUE TITLE
Unable to launch interactive scene viewer

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/fresnel#77]
## Description

I am trying to launch the interactive scene viewer within a Jupyter notebook on a remote visualization workstation, however the kernel dies.

## Script

```python
from PySide2 import QtCore
%gui qt
```

## Output

```
[I 14:03:45.649 NotebookApp] Saving file at /nucleation-event-detection/visualize.ipynb
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-org.kde.kwin.qpa, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[I 14:04:45.116 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel e453b771-8d28-406d-9e5e-7d0ccf4bf7d0 restarted
[redacted]/lib/python3.7/site-packages/jupyter_client/connect.py:163: RuntimeWarning: Failed to set sticky bit on '[redacted]/.local/share/jupyter/runtime/kernel-e453b771-8d28-406d-9e5e-7d0ccf4bf7d0.json': [Errno 22] Invalid argument: '[redacted]/.local/share/jupyter/runtime/kernel-e453b771-8d28-406d-9e5e-7d0ccf4bf7d0.json'
Probably not a big deal, but runtime files may be cleaned up periodically.
  RuntimeWarning,
```
## Expected output

I would expect the kernel not to die.

## Configuration

Platform: Linux, GPU

Installation method:
- glotzerlab-software container

Versions:
- Python version: 3.7.2
- Fresnel version: 0.8.0

## Developer

Maybe.

**Comment by joaander** [comment]
`could not connect to display` is expected behavior when attempting to launch GUI scripts in a remote terminal that is not connected to a display. There is no way that a change to frensel alter this behavior.

Are you certain you are running this with the `glotzerlab-software` container? I get
```
ImportError: No module named 'PySide2'
```
with the container, as it does not include PySide2.

Testing with a local installation, there are two ways to enable interactive widgets with remote sessions.

1. Connect with ssh forwarding, and start `jupyter` **in that session**. You can inspect the value of the environment variable `$DISPLAY` to ensure that the display is set prior to launching `juptyer`
```
user@localhost $ ssh -Y remotehost
user@remotehost $ jupyter notebook
```
This method will be slow and unusable on WAN connections, but might be OK on a local LAN.

2. Connect to the remote host with tunneling of the VNC connection and start a TurboVNC session:
```
user@localhost $ ssh -L 5902:localhost:5902 remotehost
user@remotehost $ vncserver :2
```
Launch the TurboVNC viewer on the local host. Launch jupyter **in the remote deskop session**. PySide2 windows will appear in the remote desktop. With appropriate settings, TurboVNC can be extremely responsive over both LAN and WAN connections.

**Comment by csadorf** [comment]
> `could not connect to display` is expected behavior when attempting to launch GUI scripts in a remote terminal that is not connected to a display. There is no way that a change to frensel alter this behavior.

Yes, I didn't realize that this was the issue when I first encountered it, but decided to file the bug report anyways. This is clearly *not* directly related to fresnel.
> 
> Are you certain you are running this with the `glotzerlab-software` container? I get
> 
No, I am sorry about providing inaccurate information. This was tested in the vizlab with the PySide/Qt libraries provided by the native software environment.

> Testing with a local installation, there are two ways to enable interactive widgets with remote sessions.
> 
> 1. Connect with ssh forwarding, and start `jupyter` **in that session**. You can inspect the value of the environment variable `$DISPLAY` to ensure that the display is set prior to launching `juptyer`
> 
> ```
> user@localhost $ ssh -Y remotehost
> user@remotehost $ jupyter notebook
> ```
> This method will be slow and unusable on WAN connections, but might be OK on a local LAN.
> 
> 1. Connect to the remote host with tunneling of the VNC connection and start a TurboVNC session:
> 
> ```
> user@localhost $ ssh -L 5902:localhost:5902 remotehost
> user@remotehost $ vncserver :2
> ```
> Launch the TurboVNC viewer on the local host. Launch jupyter **in the remote deskop session**. PySide2 windows will appear in the remote desktop. With appropriate settings, TurboVNC can be extremely responsive over both LAN and WAN connections.

Thank you for providing guidance on how to enable remote visualization.
